package uz.AlpinistEdu_Service.enums;

public enum UserState {
    GET_CONTACT,
    SHOW_MAIN_MENU,
    ADMIN_ADD_TEACHER,
    ADMIN_GUESTS_MENU, SHOW_SECOND_INNER_MENU, SHOW_SECOND_MENU, GRADING_STUDENTS;
}